services:
  mysql8:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: invex_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  employees-service:
    image: jacmen2005/employees-service:latest
    container_name: employees-service
    restart: always
    depends_on:
      - mysql8
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql8:3306/invex_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: root123

volumes:
  mysql_data: