spring:
  application:
    name: employees-service


  datasource:
    url: jdbc:mysql://localhost:3306/invex_db?serverTimezone=UTC
    #url: jdbc:mysql://mysql8:3306/msvc_usuarios?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings
  endpoint:
    health:
      show-details: always
      #show-details: never

logging:
  level:
    com.invex.employees: INFO